
=pod

=head1 ArduinoTap : an Unit Testing library

=head2 Introduction

ArduinoTap is a C/C++ port of the Perl5 module
L<Test::More|http://search.cpan.org/~mschwern/Test-Simple/> on Arduino.

It uses the L<Test Anything Protocol|http://en.wikipedia.org/wiki/Test_Anything_Protocol> as output,
that allows a compatibility with the Perl QA ecosystem.
For example, L<prove|http://search.cpan.org/~andya/Test-Harness/bin/prove> a basic CLI,
or L<Smolder|http://search.cpan.org/~wonko/Smolder/> a Web-based Smoke Test Aggregator Server.

It allows a simple and efficient way to write tests (without OO style).

Some tests could be marked as TODO or skipped.

An additional script C<runino> allows to build a sketch, to upload it on an Arduino board, and
to capture its output. So, it is possible to use a continuous integration server which run
a test suite containing many sketches.

    prove --exec=runino examples/*ok/*.ino examples/is*/*.ino

=head2 Bibliography

=over

=item Ian Langworth, chromatic, L<Perl Testing|http://oreilly.com/catalog/9780596100926> O'Reilly, 2005

=back

=head2 Download

ArduinoTap source can be downloaded from L<GitHub|http://github.com/fperrad/ArduinoTap/downloads/>.

=head2 Installation

The easiest way to install ArduinoTap is :

    make install

=head2 Copyright and License

Copyright 2011 FranE<ccedil>ois Perrad

This library is licensed under the terms of the Artistic License 2.0, like Perl.

=cut
